import Navbar from "./navbar";
import Head from 'next/head'
import Footer from "./footer";

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Kamari</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar></Navbar>
            <main>{children}</main>
            <Footer></Footer>

        </>
    )
}